In [1]:
import torch
import numpy as np


In [3]:
data = [[1,2],[3,5]]

In [4]:
np.array(data)

array([[1, 2],
       [3, 5]])

In [5]:
torch.tensor(data)

tensor([[1, 2],
        [3, 5]])

In [6]:
data = torch.tensor(data)

In [8]:
type(data)

torch.Tensor

In [9]:
numpy_array=np.random.rand(3,3)

In [10]:
numpy_array

array([[0.31897526, 0.0661348 , 0.11004607],
       [0.95786325, 0.47104215, 0.73584034],
       [0.85754994, 0.59602534, 0.33705678]])

In [11]:
torch.from_numpy(numpy_array)

tensor([[0.3190, 0.0661, 0.1100],
        [0.9579, 0.4710, 0.7358],
        [0.8575, 0.5960, 0.3371]], dtype=torch.float64)

In [12]:
torch.tensor(numpy_array)

tensor([[0.3190, 0.0661, 0.1100],
        [0.9579, 0.4710, 0.7358],
        [0.8575, 0.5960, 0.3371]], dtype=torch.float64)

In [13]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
my_tensor=torch.rand(2,3)

In [17]:
my_tensor.dtype

torch.float32

In [18]:
my_tensor.device

device(type='cpu')

In [21]:
my_tensor[:,1:2]

tensor([[0.0019],
        [0.9884]])

In [22]:
my_tensor.mul(my_tensor)

tensor([[8.6432e-01, 3.4546e-06, 5.0335e-01],
        [1.1740e-02, 9.7696e-01, 3.4631e-02]])

In [23]:
my_tensor

tensor([[0.9297, 0.0019, 0.7095],
        [0.1084, 0.9884, 0.1861]])

In [24]:
my_tensor.matmul(my_tensor.T)

tensor([[1.3677, 0.2346],
        [0.2346, 1.0233]])

In [25]:
torch.matmul(my_tensor,my_tensor.T)

tensor([[1.3677, 0.2346],
        [0.2346, 1.0233]])

In [27]:
torch.cat([my_tensor,my_tensor],dim=1)

tensor([[0.9297, 0.0019, 0.7095, 0.9297, 0.0019, 0.7095],
        [0.1084, 0.9884, 0.1861, 0.1084, 0.9884, 0.1861]])

In [28]:
torch.nn.functional.softmax(my_tensor,dim=1)

tensor([[0.4550, 0.1799, 0.3651],
        [0.2226, 0.5368, 0.2406]])

In [29]:
## working with images
torch.rand(10,3,128,128)

tensor([[[[7.0690e-01, 4.2268e-01, 6.8413e-01,  ..., 5.2002e-01,
           3.5912e-01, 8.3594e-02],
          [3.8176e-01, 7.9426e-01, 1.3658e-01,  ..., 7.1027e-01,
           3.2211e-01, 5.9025e-01],
          [5.7289e-01, 5.9930e-01, 3.5518e-01,  ..., 8.4376e-01,
           3.3737e-01, 7.3620e-01],
          ...,
          [6.9456e-01, 2.8347e-01, 6.3028e-01,  ..., 3.5556e-01,
           3.9118e-01, 8.3451e-01],
          [1.7275e-02, 3.2998e-01, 9.7836e-01,  ..., 1.1089e-02,
           4.6410e-01, 3.7003e-01],
          [9.6480e-01, 3.2390e-01, 3.1826e-01,  ..., 7.5168e-01,
           4.1921e-01, 3.3528e-01]],

         [[9.2554e-01, 7.4563e-01, 4.7225e-01,  ..., 3.6076e-01,
           4.0655e-01, 5.2872e-02],
          [6.2981e-01, 5.1758e-01, 4.3311e-01,  ..., 5.0986e-01,
           3.2252e-01, 3.8905e-01],
          [7.7349e-01, 6.9009e-01, 8.0709e-01,  ..., 3.4148e-01,
           4.9026e-01, 8.2141e-01],
          ...,
          [2.2016e-01, 4.2387e-01, 1.7380e-02,  ..., 2.2369

In [30]:
my_tensor

tensor([[0.9297, 0.0019, 0.7095],
        [0.1084, 0.9884, 0.1861]])

In [31]:
my_tensor.clip(0.2,0.8)

tensor([[0.8000, 0.2000, 0.7095],
        [0.2000, 0.8000, 0.2000]])

In [32]:
my_tensor.cpu().detach().numpy()

array([[0.92968583, 0.00185865, 0.7094734 ],
       [0.10835165, 0.9884112 , 0.18609422]], dtype=float32)